version: "2.1"
services:
  code-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - PASSWORD=vscode
      - SUDO_PASSWORD=P@ssw0rd!
      - TZ=Asia/Seoul
    volumes:
      - ./config:/config
    ports:
      - 80:8443
    restart: unless-stopped
